# Generated by Django 3.1.1 on 2020-10-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=200)),
                ('author', models.CharField(db_index=True, max_length=200)),
                ('book_summary', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=200)),
                ('author_profile', models.CharField(max_length=5000)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=200)),
                ('book_language', models.CharField(max_length=200)),
                ('book_pages', models.IntegerField(blank=True, null=True)),
                ('book_isbn', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_app.category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
