# Generated by Django 3.1.1 on 2020-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_isbn',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
