# Generated by Django 3.1.1 on 2020-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20201002_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
