# Generated by Django 3.1.1 on 2020-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_summary',
            field=models.TextField(max_length=5000),
        ),
    ]
