# Generated by Django 3.1.1 on 2020-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_auto_20201002_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_profile',
            field=models.TextField(max_length=5000),
        ),
    ]
