# Generated by Django 3.1.1 on 2020-10-13 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_auto_20201007_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='book',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
