# Generated by Django 3.1.1 on 2020-10-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_auto_20201012_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('book_name',)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='edition',
            new_name='book_edition',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='book_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='book_name',
        ),
    ]
