# Generated by Django 3.1.1 on 2020-11-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
    ]
